site_name: Wolotify
site_description: A journey through the world of deep wolof
theme:
  name: material
  font:
    text: Space Grotesk
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/w
  features:
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: cyan

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: cyan
      accent: deep purple

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@wolofity
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/wolofity
    
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/wolofity

copyright: Copyright &copy; 2025, Wolotify

plugins:
  - search
  - blog:
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      categories_allowed:
        - Tech
        - Lifestyle
        - Life
      post_url_format: "{slug}"
  
  - tags:
      enabled: false