name: Deploy MkDocs with uv
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache uv environment
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            uv-
      
      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Generate mkdocs.yml from template
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        run: |
          envsubst < mkdocs.template.yml > mkdocs.yml

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force