name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source
  contents: read    # to checkout the code

# Prevent the action from running multiple times in parallel
concurrency: pages-build-and-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Generate mkdocs.yml from template
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        run: |
          envsubst < mkdocs.template.yml > mkdocs.yml
          echo "✅ mkdocs.yml generated successfully"
          if grep -q "\$GOOGLE_ANALYTICS_ID" mkdocs.yml; then
            echo "❌ ERROR: GOOGLE_ANALYTICS_ID was not substituted!"
            exit 1
          fi

      - name: Cache MkDocs assets
        uses: actions/cache@v4
        with:
          key: mkdocs-${{ hashFiles('mkdocs.yml') }}
          path: .cache

      - name: Build site
        run: uv run mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

      - name: Minimize uv cache
        run: uv cache prune --ci

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4